name: Node app

on:
  push:
    branches: ["Main"]

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node-18

    # strategy:
    #   matrix:
    #     node-version: [14.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm start